// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.0
package repositories

const (
	TaskIndexLabelDescEqual     = "d4" // perfect-match of Desc
	TaskIndexLabelDescLike      = "d3" // like-match of Desc
	TaskIndexLabelDescPrefix    = "d1" // prefix-match of Desc
	TaskIndexLabelDescSuffix    = "d2" // suffix-match of Desc
	TaskIndexLabelDonePrefix    = "d5" // prefix-match of Done
	TaskIndexLabelDoneSuffix    = "d6" // suffix-match of Done
	TaskIndexLabelDoneLike      = "d7" // like-match of Done
	TaskIndexLabelDoneEqual     = "d8" // perfect-match of Done
	TaskIndexLabelCountPrefix   = "c1" // prefix-match of Count
	TaskIndexLabelCountSuffix   = "c2" // suffix-match of Count
	TaskIndexLabelCountLike     = "c3" // like-match of Count
	TaskIndexLabelCountEqual    = "c4" // perfect-match of Count
	TaskIndexLabelCreatedPrefix = "c5" // prefix-match of Created
	TaskIndexLabelCreatedSuffix = "c6" // suffix-match of Created
	TaskIndexLabelCreatedLike   = "c7" // like-match of Created
	TaskIndexLabelCreatedEqual  = "c8" // perfect-match of Created
)
