// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package repositories

const (
	EventIndexLabelBillingMonthPrefix = "b1" // prefix-match of BillingMonth
	EventIndexLabelBillingMonthSuffix = "b2" // suffix-match of BillingMonth
	EventIndexLabelBillingMonthLike   = "b3" // like-match of BillingMonth
	EventIndexLabelBillingMonthEqual  = "b4" // perfect-match of BillingMonth
	EventIndexLabelStatusEqual        = "s4" // perfect-match of Status
	EventIndexLabelStatusLike         = "s3" // like-match of Status
	EventIndexLabelStatusPrefix       = "s1" // prefix-match of Status
	EventIndexLabelStatusSuffix       = "s2" // suffix-match of Status
	EventIndexLabelCreatedAtPrefix    = "c1" // prefix-match of CreatedAt
	EventIndexLabelCreatedAtSuffix    = "c2" // suffix-match of CreatedAt
	EventIndexLabelCreatedAtLike      = "c3" // like-match of CreatedAt
	EventIndexLabelCreatedAtEqual     = "c4" // perfect-match of CreatedAt
	EventIndexLabelCreatedByEqual     = "c8" // perfect-match of CreatedBy
	EventIndexLabelCreatedByLike      = "c7" // like-match of CreatedBy
	EventIndexLabelCreatedByPrefix    = "c5" // prefix-match of CreatedBy
	EventIndexLabelCreatedBySuffix    = "c6" // suffix-match of CreatedBy
	EventIndexLabelUpdatedAtPrefix    = "u1" // prefix-match of UpdatedAt
	EventIndexLabelUpdatedAtSuffix    = "u2" // suffix-match of UpdatedAt
	EventIndexLabelUpdatedAtLike      = "u3" // like-match of UpdatedAt
	EventIndexLabelUpdatedAtEqual     = "u4" // perfect-match of UpdatedAt
	EventIndexLabelUpdatedByEqual     = "u8" // perfect-match of UpdatedBy
	EventIndexLabelUpdatedByLike      = "u7" // like-match of UpdatedBy
	EventIndexLabelUpdatedByPrefix    = "u5" // prefix-match of UpdatedBy
	EventIndexLabelUpdatedBySuffix    = "u6" // suffix-match of UpdatedBy
	EventIndexLabelDeletedAtPrefix    = "d1" // prefix-match of DeletedAt
	EventIndexLabelDeletedAtSuffix    = "d2" // suffix-match of DeletedAt
	EventIndexLabelDeletedAtLike      = "d3" // like-match of DeletedAt
	EventIndexLabelDeletedAtEqual     = "d4" // perfect-match of DeletedAt
	EventIndexLabelDeletedByEqual     = "d8" // perfect-match of DeletedBy
	EventIndexLabelDeletedByLike      = "d7" // like-match of DeletedBy
	EventIndexLabelDeletedByPrefix    = "d5" // prefix-match of DeletedBy
	EventIndexLabelDeletedBySuffix    = "d6" // suffix-match of DeletedBy
	EventIndexLabelVersionPrefix      = "v1" // prefix-match of Version
	EventIndexLabelVersionSuffix      = "v2" // suffix-match of Version
	EventIndexLabelVersionLike        = "v3" // like-match of Version
	EventIndexLabelVersionEqual       = "v4" // perfect-match of Version
)
