linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  revive:
    ignore-generated-header: false
    confidence: 0.3
    severity: "warning"
    rules:
      - name: exported
        severity: error
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
    ignore-words: []

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gofmt
    - goimports
    - revive
    - govet
    - ineffassign
    - misspell
    - exportloopref
    - staticcheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude:
    - declaration of "(err|ctx)" shadows declaration at
    - echo
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gomnd
    - path: _repository\.go
      linters:
        - dupl
    - path: model/
      linters:
        - dupl
    - path: _service\.go
      linters:
        - dupl
    - linters:
        - staticcheck
      text: "SA1019: xerrors."
