x-api-base: &api-base
  volumes:
    - ./:/app
  env_file:
    - .env

services:
  general-api:
    <<: *api-base
    build:
      context: .
      dockerfile: docker/backend/general/dev/Dockerfile
    ports:
      - target: 1234
        published: 27001
      - target: 2345
        published: 2345
    profiles:
      - general
    networks:
      - database
    depends_on:
      - firebase

  batch-api:
    <<: *api-base
    build:
      context: .
      dockerfile: docker/backend/batch/dev/Dockerfile
    ports:
      - target: 1234
        published: 27002
      - target: 2346
        published: 2346
    profiles:
      - batch
    networks:
      - database
    depends_on:
      - firebase

  cloud-sdk:
    image: google/cloud-sdk:491.0.0-alpine
    environment:
      - CLOUDSDK_CONFIG=/root/cloudsdk_config/
    volumes:
      - ./docker/cloudsdk_config:/root/cloudsdk_config/
    profiles:
      - cloud-sdk

  firebase:
    build:
      context: .
      dockerfile: ./docker/firebase/Dockerfile
    ports:
      - 8080:8080 # Cloud Firestore
      - 9199:9199 # Cloud Storage
      - 4000:4000 # Emulator Suite UI
    volumes:
      - ./docker/firebase/.firebaserc:/firebase/.firebaserc
      - ./docker/firebase/firebase.json:/firebase/firebase.json
      - ./docker/firebase/storage.rules:/firebase/storage.rules
      - ./docker/firebase/backup:/firebase/backup
      - ./docker/firebase/bin/:/root/.cache:cached
      - ./docker/firebase/config/:/root/.config:cached
    tty: true
    working_dir: /firebase
    command: firebase emulators:start --import=backup/data --export-on-exit
    networks:
      - database

  pubsub-emulator:
    container_name: pubsub-emulator
    build:
      context: ./docker/pubsub
      dockerfile: Dockerfile
    restart: always
    environment:
      - PUBSUB_PROJECT_ID=test-project
      - PUBSUB_TOPIC_ID=test-topic
      - PUBSUB_SUBSCRIPTION_ID=test-subscription
      - PUBSUB_EMULATOR_HOST=0.0.0.0:8085
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./docker/pubsub:/code
    command: 
      ./pubsub/entrypoint.sh
    ports:
      - 8085:8085
    networks:
      - database

  subscriber:
    container_name: subscriber
    build:
      context: ./docker/subscriber
      dockerfile: Dockerfile
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - PUBSUB_PROJECT_ID=test-project
      - PUBSUB_SUBSCRIPTION_ID=test-subscription
    working_dir: /app
    command: python subscriber.py
    networks:
      - database

networks:
  database:
