x-api-base: &api-base
  volumes:
    - ./:/app
  env_file:
    - .env

services:
  general-api:
    <<: *api-base
    build:
      context: .
      dockerfile: docker/backend/general/dev/Dockerfile
    ports:
      - target: 1234
        published: 27001
    profiles:
      - general
    networks:
      - database
    depends_on:
      - firestore

  app:
    container_name: gcim-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 3000:3000
      - 1313:1313
    volumes:
      - ./:/app
    depends_on:
      - firestore

  cloud-sdk:
    image: google/cloud-sdk:491.0.0-alpine
    environment:
      - CLOUDSDK_CONFIG=/root/cloudsdk_config/
    volumes:
      - ./docker/cloudsdk_config:/root/cloudsdk_config/
    profiles:
      - cloud-sdk

  firestore:
    build:
      context: .
      dockerfile: ./docker/firestore/Dockerfile
    ports:
      - 8080:8080 # Cloud Firestore
      - 4000:4000 # Emulator Suite UI
    volumes:
      - ./docker/firestore/.firebaserc:/firestore/.firebaserc
      - ./docker/firestore/firebase.json:/firestore/firebase.json
      - ./docker/firestore/backup:/firestore/backup
      - ./docker/firestore/bin/:/root/.cache:cached
      - ./docker/firestore/config/:/root/.config:cached
    tty: true
    working_dir: /firestore
    command: firebase emulators:start --import=backup/data --export-on-exit
    networks:
      - database

networks:
  database:
