// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package infrastructures

const (
	AuthIndexLabelEventIdEqual       = "e4" // perfect-match of EventId
	AuthIndexLabelEventIdLike        = "e3" // like-match of EventId
	AuthIndexLabelEventIdPrefix      = "e1" // prefix-match of EventId
	AuthIndexLabelEventIdSuffix      = "e2" // suffix-match of EventId
	AuthIndexLabelAccessTokenEqual   = "a4" // perfect-match of AccessToken
	AuthIndexLabelAccessTokenLike    = "a3" // like-match of AccessToken
	AuthIndexLabelAccessTokenPrefix  = "a1" // prefix-match of AccessToken
	AuthIndexLabelAccessTokenSuffix  = "a2" // suffix-match of AccessToken
	AuthIndexLabelRefreshTokenEqual  = "r4" // perfect-match of RefreshToken
	AuthIndexLabelRefreshTokenLike   = "r3" // like-match of RefreshToken
	AuthIndexLabelRefreshTokenPrefix = "r1" // prefix-match of RefreshToken
	AuthIndexLabelRefreshTokenSuffix = "r2" // suffix-match of RefreshToken
	AuthIndexLabelCreatedAtPrefix    = "c1" // prefix-match of CreatedAt
	AuthIndexLabelCreatedAtSuffix    = "c2" // suffix-match of CreatedAt
	AuthIndexLabelCreatedAtLike      = "c3" // like-match of CreatedAt
	AuthIndexLabelCreatedAtEqual     = "c4" // perfect-match of CreatedAt
	AuthIndexLabelCreatedByEqual     = "c8" // perfect-match of CreatedBy
	AuthIndexLabelCreatedByLike      = "c7" // like-match of CreatedBy
	AuthIndexLabelCreatedByPrefix    = "c5" // prefix-match of CreatedBy
	AuthIndexLabelCreatedBySuffix    = "c6" // suffix-match of CreatedBy
	AuthIndexLabelUpdatedAtPrefix    = "u1" // prefix-match of UpdatedAt
	AuthIndexLabelUpdatedAtSuffix    = "u2" // suffix-match of UpdatedAt
	AuthIndexLabelUpdatedAtLike      = "u3" // like-match of UpdatedAt
	AuthIndexLabelUpdatedAtEqual     = "u4" // perfect-match of UpdatedAt
	AuthIndexLabelUpdatedByEqual     = "u8" // perfect-match of UpdatedBy
	AuthIndexLabelUpdatedByLike      = "u7" // like-match of UpdatedBy
	AuthIndexLabelUpdatedByPrefix    = "u5" // prefix-match of UpdatedBy
	AuthIndexLabelUpdatedBySuffix    = "u6" // suffix-match of UpdatedBy
	AuthIndexLabelDeletedAtPrefix    = "d1" // prefix-match of DeletedAt
	AuthIndexLabelDeletedAtSuffix    = "d2" // suffix-match of DeletedAt
	AuthIndexLabelDeletedAtLike      = "d3" // like-match of DeletedAt
	AuthIndexLabelDeletedAtEqual     = "d4" // perfect-match of DeletedAt
	AuthIndexLabelDeletedByEqual     = "d8" // perfect-match of DeletedBy
	AuthIndexLabelDeletedByLike      = "d7" // like-match of DeletedBy
	AuthIndexLabelDeletedByPrefix    = "d5" // prefix-match of DeletedBy
	AuthIndexLabelDeletedBySuffix    = "d6" // suffix-match of DeletedBy
	AuthIndexLabelVersionPrefix      = "v1" // prefix-match of Version
	AuthIndexLabelVersionSuffix      = "v2" // suffix-match of Version
	AuthIndexLabelVersionLike        = "v3" // like-match of Version
	AuthIndexLabelVersionEqual       = "v4" // perfect-match of Version
)
