// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package infrastructures

import (
	"context"
	"time"

	"cloud.google.com/go/firestore"
	"golang.org/x/xerrors"
	"google.golang.org/api/iterator"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	model "github.com/topgate/gcim-temporary/back/app/internal/volcago"
)

//go:generate ../../../../../bin/mockgen -source $GOFILE -destination mocks/email_transaction_gen.go

// EmailTransactionRepository - Repository of EmailTransaction
type EmailTransactionRepository interface {
	// Single
	Get(ctx context.Context, id string, opts ...GetOption) (*model.EmailTransaction, error)
	GetWithDoc(ctx context.Context, doc *firestore.DocumentRef, opts ...GetOption) (*model.EmailTransaction, error)
	Insert(ctx context.Context, subject *model.EmailTransaction) (_ string, err error)
	Update(ctx context.Context, subject *model.EmailTransaction) (err error)
	StrictUpdate(ctx context.Context, id string, param *EmailTransactionUpdateParam, opts ...firestore.Precondition) error
	Delete(ctx context.Context, subject *model.EmailTransaction, opts ...DeleteOption) (err error)
	DeleteByID(ctx context.Context, id string, opts ...DeleteOption) (err error)
	// Multiple
	GetMulti(ctx context.Context, ids []string, opts ...GetOption) ([]*model.EmailTransaction, error)
	InsertMulti(ctx context.Context, subjects []*model.EmailTransaction) (_ []string, er error)
	UpdateMulti(ctx context.Context, subjects []*model.EmailTransaction) (er error)
	DeleteMulti(ctx context.Context, subjects []*model.EmailTransaction, opts ...DeleteOption) (er error)
	DeleteMultiByIDs(ctx context.Context, ids []string, opts ...DeleteOption) (er error)
	// Single(Transaction)
	GetWithTx(tx *firestore.Transaction, id string, opts ...GetOption) (*model.EmailTransaction, error)
	GetWithDocWithTx(tx *firestore.Transaction, doc *firestore.DocumentRef, opts ...GetOption) (*model.EmailTransaction, error)
	InsertWithTx(ctx context.Context, tx *firestore.Transaction, subject *model.EmailTransaction) (_ string, err error)
	UpdateWithTx(ctx context.Context, tx *firestore.Transaction, subject *model.EmailTransaction) (err error)
	StrictUpdateWithTx(tx *firestore.Transaction, id string, param *EmailTransactionUpdateParam, opts ...firestore.Precondition) error
	DeleteWithTx(ctx context.Context, tx *firestore.Transaction, subject *model.EmailTransaction, opts ...DeleteOption) (err error)
	DeleteByIDWithTx(ctx context.Context, tx *firestore.Transaction, id string, opts ...DeleteOption) (err error)
	// Multiple(Transaction)
	GetMultiWithTx(tx *firestore.Transaction, ids []string, opts ...GetOption) ([]*model.EmailTransaction, error)
	InsertMultiWithTx(ctx context.Context, tx *firestore.Transaction, subjects []*model.EmailTransaction) (_ []string, er error)
	UpdateMultiWithTx(ctx context.Context, tx *firestore.Transaction, subjects []*model.EmailTransaction) (er error)
	DeleteMultiWithTx(ctx context.Context, tx *firestore.Transaction, subjects []*model.EmailTransaction, opts ...DeleteOption) (er error)
	DeleteMultiByIDsWithTx(ctx context.Context, tx *firestore.Transaction, ids []string, opts ...DeleteOption) (er error)
	// Search
	Search(ctx context.Context, param *EmailTransactionSearchParam, q *firestore.Query) ([]*model.EmailTransaction, error)
	SearchWithTx(tx *firestore.Transaction, param *EmailTransactionSearchParam, q *firestore.Query) ([]*model.EmailTransaction, error)
	SearchByParam(ctx context.Context, param *EmailTransactionSearchParam) ([]*model.EmailTransaction, *PagingResult, error)
	SearchByParamWithTx(tx *firestore.Transaction, param *EmailTransactionSearchParam) ([]*model.EmailTransaction, *PagingResult, error)
	// misc
	GetCollection() *firestore.CollectionRef
	GetCollectionName() string
	GetDocRef(id string) *firestore.DocumentRef
	RunInTransaction() func(ctx context.Context, f func(context.Context, *firestore.Transaction) error, opts ...firestore.TransactionOption) (err error)
}

// EmailTransactionRepositoryMiddleware - middleware of EmailTransactionRepository
type EmailTransactionRepositoryMiddleware interface {
	BeforeInsert(ctx context.Context, subject *model.EmailTransaction) (bool, error)
	BeforeUpdate(ctx context.Context, old, subject *model.EmailTransaction) (bool, error)
	BeforeDelete(ctx context.Context, subject *model.EmailTransaction, opts ...DeleteOption) (bool, error)
	BeforeDeleteByID(ctx context.Context, ids []string, opts ...DeleteOption) (bool, error)
}

type emailTransactionRepository struct {
	collectionName   string
	firestoreClient  *firestore.Client
	middleware       []EmailTransactionRepositoryMiddleware
	uniqueRepository *uniqueRepository
}

// NewEmailTransactionRepository - constructor
func NewEmailTransactionRepository(firestoreClient *firestore.Client, middleware ...EmailTransactionRepositoryMiddleware) EmailTransactionRepository {
	return &emailTransactionRepository{
		collectionName:   "EmailTransaction",
		firestoreClient:  firestoreClient,
		middleware:       middleware,
		uniqueRepository: newUniqueRepository(firestoreClient, "EmailTransaction"),
	}
}

func (repo *emailTransactionRepository) setMeta(subject *model.EmailTransaction, isInsert bool) {
	now := time.Now()

	if isInsert {
		subject.CreatedAt = now
	}
	subject.UpdatedAt = now
	subject.Version++
}

func (repo *emailTransactionRepository) setMetaWithStrictUpdate(param *EmailTransactionUpdateParam) {
	param.UpdatedAt = firestore.ServerTimestamp
	param.Version = firestore.Increment(1)
}

func (repo *emailTransactionRepository) beforeInsert(ctx context.Context, subject *model.EmailTransaction) error {
	if subject.Version != 0 {
		return xerrors.Errorf("insert data must be Version == 0 %+v: %w", subject, ErrVersionConflict)
	}
	if subject.DeletedAt != nil {
		return xerrors.Errorf("insert data must be DeletedAt == nil: %+v", subject)
	}
	repo.setMeta(subject, true)
	repo.uniqueRepository.setMiddleware(ctx)
	err := repo.uniqueRepository.CheckUnique(ctx, nil, subject)
	if err != nil {
		return xerrors.Errorf("unique.middleware error: %w", err)
	}

	for _, m := range repo.middleware {
		c, err := m.BeforeInsert(ctx, subject)
		if err != nil {
			return xerrors.Errorf("beforeInsert.middleware error: %w", err)
		}
		if !c {
			continue
		}
	}

	return nil
}

func (repo *emailTransactionRepository) beforeUpdate(ctx context.Context, old, subject *model.EmailTransaction) error {
	if ctx.Value(transactionInProgressKey{}) != nil && old == nil {
		var err error
		doc := repo.GetDocRef(subject.ID)
		old, err = repo.get(context.Background(), doc)
		if err != nil {
			if status.Code(err) == codes.NotFound {
				return ErrNotFound
			}
			return xerrors.Errorf("error in Get method: %w", err)
		}
	}
	if old.Version > subject.Version {
		return xerrors.Errorf(
			"The data in the database is newer: (db version: %d, target version: %d) %+v: %w",
			old.Version, subject.Version, subject, ErrVersionConflict,
		)
	}
	if subject.DeletedAt != nil {
		return xerrors.Errorf("update data must be DeletedAt == nil: %+v", subject)
	}
	repo.setMeta(subject, false)
	repo.uniqueRepository.setMiddleware(ctx)
	err := repo.uniqueRepository.CheckUnique(ctx, old, subject)
	if err != nil {
		return xerrors.Errorf("unique.middleware error: %w", err)
	}

	for _, m := range repo.middleware {
		c, err := m.BeforeUpdate(ctx, old, subject)
		if err != nil {
			return xerrors.Errorf("beforeUpdate.middleware error: %w", err)
		}
		if !c {
			continue
		}
	}

	return nil
}

func (repo *emailTransactionRepository) beforeDelete(ctx context.Context, subject *model.EmailTransaction, opts ...DeleteOption) error {
	repo.setMeta(subject, false)
	repo.uniqueRepository.setMiddleware(ctx)
	err := repo.uniqueRepository.DeleteUnique(ctx, subject)
	if err != nil {
		return xerrors.Errorf("unique.middleware error: %w", err)
	}

	for _, m := range repo.middleware {
		c, err := m.BeforeDelete(ctx, subject, opts...)
		if err != nil {
			return xerrors.Errorf("beforeDelete.middleware error: %w", err)
		}
		if !c {
			continue
		}
	}

	return nil
}

// GetCollection - *firestore.CollectionRef getter
func (repo *emailTransactionRepository) GetCollection() *firestore.CollectionRef {
	return repo.firestoreClient.Collection(repo.collectionName)
}

// GetCollectionName - CollectionName getter
func (repo *emailTransactionRepository) GetCollectionName() string {
	return repo.collectionName
}

// GetDocRef - *firestore.DocumentRef getter
func (repo *emailTransactionRepository) GetDocRef(id string) *firestore.DocumentRef {
	return repo.GetCollection().Doc(id)
}

// RunInTransaction - (*firestore.Client).RunTransaction getter
func (repo *emailTransactionRepository) RunInTransaction() func(ctx context.Context, f func(context.Context, *firestore.Transaction) error, opts ...firestore.TransactionOption) (err error) {
	return repo.firestoreClient.RunTransaction
}

// EmailTransactionSearchParam - params for search
type EmailTransactionSearchParam struct {
	ID        *QueryChainer
	EventID   *QueryChainer
	BillingID *QueryChainer
	CreatedAt *QueryChainer
	CreatedBy *QueryChainer
	UpdatedAt *QueryChainer
	UpdatedBy *QueryChainer
	DeletedAt *QueryChainer
	DeletedBy *QueryChainer
	Version   *QueryChainer

	IncludeSoftDeleted bool
	CursorKey          string
	CursorLimit        int
}

// EmailTransactionUpdateParam - params for strict updates
type EmailTransactionUpdateParam struct {
	EventID   interface{}
	BillingID interface{}
	CreatedAt interface{}
	CreatedBy interface{}
	UpdatedAt interface{}
	UpdatedBy interface{}
	DeletedAt interface{}
	DeletedBy interface{}
	Version   interface{}
}

// Search - search documents
// The third argument is firestore.Query, basically you can pass nil
func (repo *emailTransactionRepository) Search(ctx context.Context, param *EmailTransactionSearchParam, q *firestore.Query) ([]*model.EmailTransaction, error) {
	return repo.search(ctx, param, q)
}

// SearchByParam - search documents by search param
func (repo *emailTransactionRepository) SearchByParam(ctx context.Context, param *EmailTransactionSearchParam) ([]*model.EmailTransaction, *PagingResult, error) {
	return repo.searchByParam(ctx, param)
}

// Get - get `EmailTransaction` by `EmailTransaction.ID`
func (repo *emailTransactionRepository) Get(ctx context.Context, id string, opts ...GetOption) (*model.EmailTransaction, error) {
	doc := repo.GetDocRef(id)
	return repo.get(ctx, doc, opts...)
}

// GetWithDoc - get `EmailTransaction` by *firestore.DocumentRef
func (repo *emailTransactionRepository) GetWithDoc(ctx context.Context, doc *firestore.DocumentRef, opts ...GetOption) (*model.EmailTransaction, error) {
	return repo.get(ctx, doc, opts...)
}

// Insert - insert of `EmailTransaction`
func (repo *emailTransactionRepository) Insert(ctx context.Context, subject *model.EmailTransaction) (_ string, err error) {
	if err := repo.beforeInsert(ctx, subject); err != nil {
		return "", xerrors.Errorf("before insert error: %w", err)
	}

	return repo.insert(ctx, subject)
}

// Update - update of `EmailTransaction`
func (repo *emailTransactionRepository) Update(ctx context.Context, subject *model.EmailTransaction) (err error) {
	doc := repo.GetDocRef(subject.ID)

	old, err := repo.get(ctx, doc)
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return ErrNotFound
		}
		return xerrors.Errorf("error in Get method: %w", err)
	}

	if err := repo.beforeUpdate(ctx, old, subject); err != nil {
		return xerrors.Errorf("before update error: %w", err)
	}

	return repo.update(ctx, subject)
}

// StrictUpdate - strict update of `EmailTransaction`
func (repo *emailTransactionRepository) StrictUpdate(ctx context.Context, id string, param *EmailTransactionUpdateParam, opts ...firestore.Precondition) error {
	return repo.strictUpdate(ctx, id, param, opts...)
}

// Delete - delete of `EmailTransaction`
func (repo *emailTransactionRepository) Delete(ctx context.Context, subject *model.EmailTransaction, opts ...DeleteOption) (err error) {
	if err := repo.beforeDelete(ctx, subject, opts...); err != nil {
		return xerrors.Errorf("before delete error: %w", err)
	}

	if len(opts) > 0 && opts[0].Mode == DeleteModeSoft {
		t := time.Now()
		subject.DeletedAt = &t
		if err := repo.update(ctx, subject); err != nil {
			return xerrors.Errorf("error in update method: %w", err)
		}
		return nil
	}

	return repo.deleteByID(ctx, subject.ID)
}

// DeleteByID - delete `EmailTransaction` by `EmailTransaction.ID`
func (repo *emailTransactionRepository) DeleteByID(ctx context.Context, id string, opts ...DeleteOption) (err error) {
	subject, err := repo.Get(ctx, id)
	if err != nil {
		return xerrors.Errorf("error in Get method: %w", err)
	}

	if err := repo.beforeDelete(ctx, subject, opts...); err != nil {
		return xerrors.Errorf("before delete error: %w", err)
	}

	if len(opts) > 0 && opts[0].Mode == DeleteModeSoft {
		t := time.Now()
		subject.DeletedAt = &t
		if err := repo.update(ctx, subject); err != nil {
			return xerrors.Errorf("error in update method: %w", err)
		}
		return nil
	}

	return repo.Delete(ctx, subject, opts...)
}

// GetMulti - get `EmailTransaction` in bulk by array of `EmailTransaction.ID`
func (repo *emailTransactionRepository) GetMulti(ctx context.Context, ids []string, opts ...GetOption) ([]*model.EmailTransaction, error) {
	return repo.getMulti(ctx, ids, opts...)
}

// InsertMulti - bulk insert of `EmailTransaction`
func (repo *emailTransactionRepository) InsertMulti(ctx context.Context, subjects []*model.EmailTransaction) (_ []string, er error) {

	ids := make([]string, 0, len(subjects))
	batches := make([]*firestore.WriteBatch, 0)
	batch := repo.firestoreClient.Batch()
	collect := repo.GetCollection()

	for i, subject := range subjects {
		var ref *firestore.DocumentRef
		if subject.ID == "" {
			ref = collect.NewDoc()
			subject.ID = ref.ID
		} else {
			ref = collect.Doc(subject.ID)
			if s, err := ref.Get(ctx); err == nil {
				return nil, xerrors.Errorf("already exists [%v]: %#v", subject.ID, s)
			}
		}

		if err := repo.beforeInsert(ctx, subject); err != nil {
			return nil, xerrors.Errorf("before insert error(%d) [%v]: %w", i, subject.ID, err)
		}

		batch.Set(ref, subject)
		ids = append(ids, ref.ID)
		i++
		if (i%500) == 0 && len(subjects) != i {
			batches = append(batches, batch)
			batch = repo.firestoreClient.Batch()
		}
	}
	batches = append(batches, batch)

	for _, b := range batches {
		if _, err := b.Commit(ctx); err != nil {
			return nil, xerrors.Errorf("error in Commit method: %w", err)
		}
	}

	return ids, nil
}

// UpdateMulti - bulk update of `EmailTransaction`
func (repo *emailTransactionRepository) UpdateMulti(ctx context.Context, subjects []*model.EmailTransaction) (er error) {

	batches := make([]*firestore.WriteBatch, 0)
	batch := repo.firestoreClient.Batch()
	collect := repo.GetCollection()

	for i, subject := range subjects {
		ref := collect.Doc(subject.ID)
		snapShot, err := ref.Get(ctx)
		if err != nil {
			if status.Code(err) == codes.NotFound {
				return xerrors.Errorf("not found [%v]: %w", subject.ID, err)
			}
			return xerrors.Errorf("error in Get method [%v]: %w", subject.ID, err)
		}

		old := new(model.EmailTransaction)
		if err = snapShot.DataTo(&old); err != nil {
			return xerrors.Errorf("error in DataTo method: %w", err)
		}

		if err := repo.beforeUpdate(ctx, old, subject); err != nil {
			return xerrors.Errorf("before update error(%d) [%v]: %w", i, subject.ID, err)
		}

		batch.Set(ref, subject)
		i++
		if (i%500) == 0 && len(subjects) != i {
			batches = append(batches, batch)
			batch = repo.firestoreClient.Batch()
		}
	}
	batches = append(batches, batch)

	for _, b := range batches {
		if _, err := b.Commit(ctx); err != nil {
			return xerrors.Errorf("error in Commit method: %w", err)
		}
	}

	return nil
}

// DeleteMulti - bulk delete of `EmailTransaction`
func (repo *emailTransactionRepository) DeleteMulti(ctx context.Context, subjects []*model.EmailTransaction, opts ...DeleteOption) (er error) {

	batches := make([]*firestore.WriteBatch, 0)
	batch := repo.firestoreClient.Batch()
	collect := repo.GetCollection()

	for i, subject := range subjects {
		ref := collect.Doc(subject.ID)
		if _, err := ref.Get(ctx); err != nil {
			if status.Code(err) == codes.NotFound {
				return xerrors.Errorf("not found [%v]: %w", subject.ID, err)
			}
			return xerrors.Errorf("error in Get method [%v]: %w", subject.ID, err)
		}

		if err := repo.beforeDelete(ctx, subject, opts...); err != nil {
			return xerrors.Errorf("before delete error(%d) [%v]: %w", i, subject.ID, err)
		}

		if len(opts) > 0 && opts[0].Mode == DeleteModeSoft {
			t := time.Now()
			subject.DeletedAt = &t
			batch.Set(ref, subject)
		} else {
			batch.Delete(ref)
		}

		i++
		if (i%500) == 0 && len(subjects) != i {
			batches = append(batches, batch)
			batch = repo.firestoreClient.Batch()
		}
	}
	batches = append(batches, batch)

	for _, b := range batches {
		if _, err := b.Commit(ctx); err != nil {
			return xerrors.Errorf("error in Commit method: %w", err)
		}
	}

	return nil
}

// DeleteMultiByIDs - delete `EmailTransaction` in bulk by array of `EmailTransaction.ID`
func (repo *emailTransactionRepository) DeleteMultiByIDs(ctx context.Context, ids []string, opts ...DeleteOption) (er error) {
	subjects := make([]*model.EmailTransaction, len(ids))

	opt := GetOption{}
	if len(opts) > 0 {
		opt.IncludeSoftDeleted = opts[0].Mode == DeleteModeHard
	}
	for i, id := range ids {
		subject, err := repo.Get(ctx, id, opt)
		if err != nil {
			return xerrors.Errorf("error in Get method: %w", err)
		}
		subjects[i] = subject
	}

	return repo.DeleteMulti(ctx, subjects, opts...)
}

// SearchWithTx - search documents in transaction
func (repo *emailTransactionRepository) SearchWithTx(tx *firestore.Transaction, param *EmailTransactionSearchParam, q *firestore.Query) ([]*model.EmailTransaction, error) {
	return repo.search(tx, param, q)
}

// SearchByParamWithTx - search documents by search param in transaction
func (repo *emailTransactionRepository) SearchByParamWithTx(tx *firestore.Transaction, param *EmailTransactionSearchParam) ([]*model.EmailTransaction, *PagingResult, error) {
	return repo.searchByParam(tx, param)
}

// GetWithTx - get `EmailTransaction` by `EmailTransaction.ID` in transaction
func (repo *emailTransactionRepository) GetWithTx(tx *firestore.Transaction, id string, opts ...GetOption) (*model.EmailTransaction, error) {
	doc := repo.GetDocRef(id)
	return repo.get(tx, doc, opts...)
}

// GetWithDocWithTx - get `EmailTransaction` by *firestore.DocumentRef in transaction
func (repo *emailTransactionRepository) GetWithDocWithTx(tx *firestore.Transaction, doc *firestore.DocumentRef, opts ...GetOption) (*model.EmailTransaction, error) {
	return repo.get(tx, doc, opts...)
}

// InsertWithTx - insert of `EmailTransaction` in transaction
func (repo *emailTransactionRepository) InsertWithTx(ctx context.Context, tx *firestore.Transaction, subject *model.EmailTransaction) (_ string, err error) {
	if err := repo.beforeInsert(context.WithValue(ctx, transactionInProgressKey{}, tx), subject); err != nil {
		return "", xerrors.Errorf("before insert error: %w", err)
	}

	return repo.insert(tx, subject)
}

// UpdateWithTx - update of `EmailTransaction` in transaction
func (repo *emailTransactionRepository) UpdateWithTx(ctx context.Context, tx *firestore.Transaction, subject *model.EmailTransaction) (err error) {
	if err := repo.beforeUpdate(context.WithValue(ctx, transactionInProgressKey{}, tx), nil, subject); err != nil {
		return xerrors.Errorf("before update error: %w", err)
	}

	return repo.update(tx, subject)
}

// StrictUpdateWithTx - strict update of `EmailTransaction` in transaction
func (repo *emailTransactionRepository) StrictUpdateWithTx(tx *firestore.Transaction, id string, param *EmailTransactionUpdateParam, opts ...firestore.Precondition) error {
	return repo.strictUpdate(tx, id, param, opts...)
}

// DeleteWithTx - delete of `EmailTransaction` in transaction
func (repo *emailTransactionRepository) DeleteWithTx(ctx context.Context, tx *firestore.Transaction, subject *model.EmailTransaction, opts ...DeleteOption) (err error) {
	if err := repo.beforeDelete(context.WithValue(ctx, transactionInProgressKey{}, tx), subject, opts...); err != nil {
		return xerrors.Errorf("before delete error: %w", err)
	}

	if len(opts) > 0 && opts[0].Mode == DeleteModeSoft {
		t := time.Now()
		subject.DeletedAt = &t
		if err := repo.update(tx, subject); err != nil {
			return xerrors.Errorf("error in update method: %w", err)
		}
		return nil
	}

	return repo.deleteByID(tx, subject.ID)
}

// DeleteByIDWithTx - delete `EmailTransaction` by `EmailTransaction.ID` in transaction
func (repo *emailTransactionRepository) DeleteByIDWithTx(ctx context.Context, tx *firestore.Transaction, id string, opts ...DeleteOption) (err error) {
	subject, err := repo.Get(context.Background(), id)
	if err != nil {
		return xerrors.Errorf("error in Get method: %w", err)
	}

	if len(opts) > 0 && opts[0].Mode == DeleteModeSoft {
		t := time.Now()
		subject.DeletedAt = &t
		if err := repo.update(tx, subject); err != nil {
			return xerrors.Errorf("error in update method: %w", err)
		}
		return nil
	}

	if err := repo.beforeDelete(context.WithValue(ctx, transactionInProgressKey{}, tx), subject, opts...); err != nil {
		return xerrors.Errorf("before delete error: %w", err)
	}

	return repo.deleteByID(tx, id)
}

// GetMultiWithTx - get `EmailTransaction` in bulk by array of `EmailTransaction.ID` in transaction
func (repo *emailTransactionRepository) GetMultiWithTx(tx *firestore.Transaction, ids []string, opts ...GetOption) ([]*model.EmailTransaction, error) {
	return repo.getMulti(tx, ids, opts...)
}

// InsertMultiWithTx - bulk insert of `EmailTransaction` in transaction
func (repo *emailTransactionRepository) InsertMultiWithTx(ctx context.Context, tx *firestore.Transaction, subjects []*model.EmailTransaction) (_ []string, er error) {

	for i := range subjects {
		if _, err := tx.Get(new(firestore.DocumentRef)); err == nil {
			return nil, xerrors.Errorf("already exists(%d) [%v]: %w", i, subjects[i].ID, err)
		}
	}

	ids := make([]string, len(subjects))

	for i := range subjects {
		if err := repo.beforeInsert(ctx, subjects[i]); err != nil {
			return nil, xerrors.Errorf("before insert error(%d) [%v]: %w", i, subjects[i].ID, err)
		}

		id, err := repo.insert(tx, subjects[i])
		if err != nil {
			return nil, xerrors.Errorf("error in insert method(%d) [%v]: %w", i, subjects[i].ID, err)
		}
		ids[i] = id
	}

	return ids, nil
}

// UpdateMultiWithTx - bulk update of `EmailTransaction` in transaction
func (repo *emailTransactionRepository) UpdateMultiWithTx(ctx context.Context, tx *firestore.Transaction, subjects []*model.EmailTransaction) (er error) {
	ctx = context.WithValue(ctx, transactionInProgressKey{}, tx)

	for i := range subjects {
		if err := repo.beforeUpdate(ctx, nil, subjects[i]); err != nil {
			return xerrors.Errorf("before update error(%d) [%v]: %w", i, subjects[i].ID, err)
		}
	}

	for i := range subjects {
		if err := repo.update(tx, subjects[i]); err != nil {
			return xerrors.Errorf("error in update method(%d) [%v]: %w", i, subjects[i].ID, err)
		}
	}

	return nil
}

// DeleteMultiWithTx - bulk delete of `EmailTransaction` in transaction
func (repo *emailTransactionRepository) DeleteMultiWithTx(ctx context.Context, tx *firestore.Transaction, subjects []*model.EmailTransaction, opts ...DeleteOption) (er error) {

	t := time.Now()
	var isHardDeleteMode bool
	if len(opts) > 0 {
		isHardDeleteMode = opts[0].Mode == DeleteModeHard
	}
	opt := GetOption{
		IncludeSoftDeleted: isHardDeleteMode,
	}
	for i := range subjects {
		dr := repo.GetDocRef(subjects[i].ID)
		if _, err := repo.get(context.Background(), dr, opt); err != nil {
			if status.Code(err) == codes.NotFound {
				return xerrors.Errorf("not found(%d) [%v]", i, subjects[i].ID)
			}
			return xerrors.Errorf("error in get method(%d) [%v]: %w", i, subjects[i].ID, err)
		}

		if err := repo.beforeDelete(context.WithValue(ctx, transactionInProgressKey{}, tx), subjects[i], opts...); err != nil {
			return xerrors.Errorf("before delete error(%d) [%v]: %w", i, subjects[i].ID, err)
		}

		if !isHardDeleteMode {
			subjects[i].DeletedAt = &t
			if err := repo.update(tx, subjects[i]); err != nil {
				return xerrors.Errorf("error in update method(%d) [%v]: %w", i, subjects[i].ID, err)
			}
		}
	}

	if len(opts) > 0 && opts[0].Mode == DeleteModeSoft {
		return nil
	}

	for i := range subjects {
		if err := repo.deleteByID(tx, subjects[i].ID); err != nil {
			return xerrors.Errorf("error in delete method(%d) [%v]: %w", i, subjects[i].ID, err)
		}
	}

	return nil
}

// DeleteMultiByIDWithTx - delete `EmailTransaction` in bulk by array of `EmailTransaction.ID` in transaction
func (repo *emailTransactionRepository) DeleteMultiByIDsWithTx(ctx context.Context, tx *firestore.Transaction, ids []string, opts ...DeleteOption) (er error) {

	t := time.Now()
	for i := range ids {
		dr := repo.GetDocRef(ids[i])
		subject, err := repo.get(context.Background(), dr)
		if err != nil {
			if status.Code(err) == codes.NotFound {
				return xerrors.Errorf("not found(%d) [%v]", i, ids[i])
			}
			return xerrors.Errorf("error in get method(%d) [%v]: %w", i, ids[i], err)
		}

		if err := repo.beforeDelete(context.WithValue(ctx, transactionInProgressKey{}, tx), subject, opts...); err != nil {
			return xerrors.Errorf("before delete error(%d) [%v]: %w", i, subject.ID, err)
		}

		if len(opts) > 0 && opts[0].Mode == DeleteModeSoft {
			subject.DeletedAt = &t
			if err := repo.update(tx, subject); err != nil {
				return xerrors.Errorf("error in update method(%d) [%v]: %w", i, ids[i], err)
			}
		}
	}

	if len(opts) > 0 && opts[0].Mode == DeleteModeSoft {
		return nil
	}

	for i := range ids {
		if err := repo.deleteByID(tx, ids[i]); err != nil {
			return xerrors.Errorf("error in delete method(%d) [%v]: %w", i, ids[i], err)
		}
	}

	return nil
}

func (repo *emailTransactionRepository) get(v interface{}, doc *firestore.DocumentRef, opts ...GetOption) (*model.EmailTransaction, error) {
	var (
		snapShot *firestore.DocumentSnapshot
		err      error
	)

	switch x := v.(type) {
	case *firestore.Transaction:
		snapShot, err = x.Get(doc)
	case context.Context:
		snapShot, err = doc.Get(x)
	default:
		return nil, xerrors.Errorf("invalid type: %v", x)
	}

	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, ErrNotFound
		}
		return nil, xerrors.Errorf("error in Get method: %w", err)
	}

	subject := new(model.EmailTransaction)
	if err := snapShot.DataTo(&subject); err != nil {
		return nil, xerrors.Errorf("error in DataTo method: %w", err)
	}

	if len(opts) == 0 || !opts[0].IncludeSoftDeleted {
		if subject.DeletedAt != nil {
			return nil, ErrAlreadyDeleted
		}
	}
	subject.ID = snapShot.Ref.ID

	return subject, nil
}

func (repo *emailTransactionRepository) getMulti(v interface{}, ids []string, opts ...GetOption) ([]*model.EmailTransaction, error) {
	var (
		snapShots []*firestore.DocumentSnapshot
		err       error
		collect   = repo.GetCollection()
		drs       = make([]*firestore.DocumentRef, len(ids))
	)

	for i, id := range ids {
		ref := collect.Doc(id)
		drs[i] = ref
	}

	switch x := v.(type) {
	case *firestore.Transaction:
		snapShots, err = x.GetAll(drs)
	case context.Context:
		snapShots, err = repo.firestoreClient.GetAll(x, drs)
	default:
		return nil, xerrors.Errorf("invalid type: %v", v)
	}

	if err != nil {
		return nil, xerrors.Errorf("error in GetAll method: %w", err)
	}

	subjects := make([]*model.EmailTransaction, 0, len(ids))
	mErr := NewMultiErrors()
	for i, snapShot := range snapShots {
		if !snapShot.Exists() {
			mErr = append(mErr, NewMultiError(i, ErrNotFound))
			continue
		}

		subject := new(model.EmailTransaction)
		if err = snapShot.DataTo(&subject); err != nil {
			return nil, xerrors.Errorf("error in DataTo method: %w", err)
		}

		if len(opts) == 0 || !opts[0].IncludeSoftDeleted {
			if subject.DeletedAt != nil {
				mErr = append(mErr, NewMultiError(i, ErrLogicallyDeletedData))
				continue
			}
		}
		subject.ID = snapShot.Ref.ID
		subjects = append(subjects, subject)
	}

	if len(mErr) == 0 {
		return subjects, nil
	}

	return subjects, mErr
}

func (repo *emailTransactionRepository) insert(v interface{}, subject *model.EmailTransaction) (string, error) {
	var (
		dr  = repo.GetDocRef(subject.ID)
		err error
	)

	switch x := v.(type) {
	case *firestore.Transaction:
		err = x.Create(dr, subject)
	case context.Context:
		_, err = dr.Create(x, subject)
	default:
		return "", xerrors.Errorf("invalid type: %v", v)
	}

	if err != nil {
		if status.Code(err) == codes.AlreadyExists {
			return "", xerrors.Errorf("error in Create method: err=%+v: %w", err, ErrAlreadyExists)
		}
		return "", xerrors.Errorf("error in Create method: %w", err)
	}

	subject.ID = dr.ID

	return dr.ID, nil
}

func (repo *emailTransactionRepository) update(v interface{}, subject *model.EmailTransaction) error {
	var (
		dr  = repo.GetDocRef(subject.ID)
		err error
	)

	switch x := v.(type) {
	case *firestore.Transaction:
		err = x.Set(dr, subject)
	case context.Context:
		_, err = dr.Set(x, subject)
	default:
		return xerrors.Errorf("invalid type: %v", v)
	}

	if err != nil {
		return xerrors.Errorf("error in Set method: %w", err)
	}

	return nil
}

func (repo *emailTransactionRepository) strictUpdate(v interface{}, id string, param *EmailTransactionUpdateParam, opts ...firestore.Precondition) error {
	var (
		dr  = repo.GetDocRef(id)
		err error
	)

	repo.setMetaWithStrictUpdate(param)

	updates := updater(model.EmailTransaction{}, param)

	switch x := v.(type) {
	case *firestore.Transaction:
		err = x.Update(dr, updates, opts...)
	case context.Context:
		_, err = dr.Update(x, updates, opts...)
	default:
		return xerrors.Errorf("invalid type: %v", v)
	}

	if err != nil {
		return xerrors.Errorf("error in Update method: %w", err)
	}

	return nil
}

func (repo *emailTransactionRepository) deleteByID(v interface{}, id string) error {
	dr := repo.GetDocRef(id)
	var err error

	switch x := v.(type) {
	case *firestore.Transaction:
		err = x.Delete(dr, firestore.Exists)
	case context.Context:
		_, err = dr.Delete(x, firestore.Exists)
	default:
		return xerrors.Errorf("invalid type: %v", v)
	}

	if err != nil {
		return xerrors.Errorf("error in Delete method: %w", err)
	}

	return nil
}

func (repo *emailTransactionRepository) runQuery(v interface{}, query firestore.Query) ([]*model.EmailTransaction, error) {
	var iter *firestore.DocumentIterator

	switch x := v.(type) {
	case *firestore.Transaction:
		iter = x.Documents(query)
	case context.Context:
		iter = query.Documents(x)
	default:
		return nil, xerrors.Errorf("invalid type: %v", v)
	}

	defer iter.Stop()

	subjects := make([]*model.EmailTransaction, 0)

	for {
		doc, err := iter.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return nil, xerrors.Errorf("error in Next method: %w", err)
		}

		subject := new(model.EmailTransaction)

		if err = doc.DataTo(&subject); err != nil {
			return nil, xerrors.Errorf("error in DataTo method: %w", err)
		}

		subject.ID = doc.Ref.ID
		subjects = append(subjects, subject)
	}

	return subjects, nil
}

// BUG(54m): there may be potential bugs
func (repo *emailTransactionRepository) searchByParam(v interface{}, param *EmailTransactionSearchParam) ([]*model.EmailTransaction, *PagingResult, error) {
	query := func() firestore.Query {
		return repo.GetCollection().Query
	}()
	if param.ID != nil {
		for _, chain := range param.ID.QueryGroup {
			var value interface{}
			switch val := chain.Value.(type) {
			case string:
				value = repo.GetDocRef(val)
			case []string:
				docRefs := make([]*firestore.DocumentRef, len(val))
				for i := range val {
					docRefs[i] = repo.GetDocRef(val[i])
				}
				value = docRefs
			default:
				return nil, nil, xerrors.Errorf("document id can only be of type `string` and `[]string`. value: %#v", chain.Value)
			}
			query = query.Where(firestore.DocumentID, chain.Operator, value)
		}
		if direction := param.ID.OrderByDirection; direction > 0 {
			query = query.OrderBy(firestore.DocumentID, direction)
			query = param.ID.BuildCursorQuery(query)
		}
	}
	if param.EventID != nil {
		for _, chain := range param.EventID.QueryGroup {
			query = query.Where("EventID", chain.Operator, chain.Value)
		}
		if direction := param.EventID.OrderByDirection; direction > 0 {
			query = query.OrderBy("EventID", direction)
			query = param.EventID.BuildCursorQuery(query)
		}
	}
	if param.BillingID != nil {
		for _, chain := range param.BillingID.QueryGroup {
			query = query.Where("BillingID", chain.Operator, chain.Value)
		}
		if direction := param.BillingID.OrderByDirection; direction > 0 {
			query = query.OrderBy("BillingID", direction)
			query = param.BillingID.BuildCursorQuery(query)
		}
	}
	if param.CreatedAt != nil {
		for _, chain := range param.CreatedAt.QueryGroup {
			query = query.Where("CreatedAt", chain.Operator, chain.Value)
		}
		if direction := param.CreatedAt.OrderByDirection; direction > 0 {
			query = query.OrderBy("CreatedAt", direction)
			query = param.CreatedAt.BuildCursorQuery(query)
		}
	}
	if param.CreatedBy != nil {
		for _, chain := range param.CreatedBy.QueryGroup {
			query = query.Where("CreatedBy", chain.Operator, chain.Value)
		}
		if direction := param.CreatedBy.OrderByDirection; direction > 0 {
			query = query.OrderBy("CreatedBy", direction)
			query = param.CreatedBy.BuildCursorQuery(query)
		}
	}
	if param.UpdatedAt != nil {
		for _, chain := range param.UpdatedAt.QueryGroup {
			query = query.Where("UpdatedAt", chain.Operator, chain.Value)
		}
		if direction := param.UpdatedAt.OrderByDirection; direction > 0 {
			query = query.OrderBy("UpdatedAt", direction)
			query = param.UpdatedAt.BuildCursorQuery(query)
		}
	}
	if param.UpdatedBy != nil {
		for _, chain := range param.UpdatedBy.QueryGroup {
			query = query.Where("UpdatedBy", chain.Operator, chain.Value)
		}
		if direction := param.UpdatedBy.OrderByDirection; direction > 0 {
			query = query.OrderBy("UpdatedBy", direction)
			query = param.UpdatedBy.BuildCursorQuery(query)
		}
	}
	if param.DeletedAt != nil {
		for _, chain := range param.DeletedAt.QueryGroup {
			query = query.Where("DeletedAt", chain.Operator, chain.Value)
		}
		if direction := param.DeletedAt.OrderByDirection; direction > 0 {
			query = query.OrderBy("DeletedAt", direction)
			query = param.DeletedAt.BuildCursorQuery(query)
		}
	}
	if param.DeletedBy != nil {
		for _, chain := range param.DeletedBy.QueryGroup {
			query = query.Where("DeletedBy", chain.Operator, chain.Value)
		}
		if direction := param.DeletedBy.OrderByDirection; direction > 0 {
			query = query.OrderBy("DeletedBy", direction)
			query = param.DeletedBy.BuildCursorQuery(query)
		}
	}
	if param.Version != nil {
		for _, chain := range param.Version.QueryGroup {
			query = query.Where("Version", chain.Operator, chain.Value)
		}
		if direction := param.Version.OrderByDirection; direction > 0 {
			query = query.OrderBy("Version", direction)
			query = param.Version.BuildCursorQuery(query)
		}
	}
	if !param.IncludeSoftDeleted {
		query = query.Where("DeletedAt", OpTypeEqual, nil)
	}

	limit := param.CursorLimit + 1

	if param.CursorKey != "" {
		var (
			ds  *firestore.DocumentSnapshot
			err error
		)
		switch x := v.(type) {
		case *firestore.Transaction:
			ds, err = x.Get(repo.GetDocRef(param.CursorKey))
		case context.Context:
			ds, err = repo.GetDocRef(param.CursorKey).Get(x)
		default:
			return nil, nil, xerrors.Errorf("invalid x type: %v", v)
		}
		if err != nil {
			if status.Code(err) == codes.NotFound {
				return nil, nil, ErrNotFound
			}
			return nil, nil, xerrors.Errorf("error in Get method: %w", err)
		}
		query = query.StartAt(ds)
	}

	if limit > 1 {
		query = query.Limit(limit)
	}

	subjects, err := repo.runQuery(v, query)
	if err != nil {
		return nil, nil, xerrors.Errorf("error in runQuery method: %w", err)
	}

	pagingResult := &PagingResult{
		Length: len(subjects),
	}
	if limit > 1 && limit == pagingResult.Length {
		next := pagingResult.Length - 1
		pagingResult.NextCursorKey = subjects[next].ID
		subjects = subjects[:next]
		pagingResult.Length--
	}

	return subjects, pagingResult, nil
}

func (repo *emailTransactionRepository) search(v interface{}, param *EmailTransactionSearchParam, q *firestore.Query) ([]*model.EmailTransaction, error) {
	if (param == nil && q == nil) || (param != nil && q != nil) {
		return nil, xerrors.New("either one should be nil")
	}

	query := func() firestore.Query {
		if q != nil {
			return *q
		}
		return repo.GetCollection().Query
	}()

	if q == nil {
		subjects, _, err := repo.searchByParam(v, param)
		if err != nil {
			return nil, xerrors.Errorf("error in searchByParam method: %w", err)
		}

		return subjects, nil
	}

	return repo.runQuery(v, query)
}
