// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package infrastructures

const (
	EventStatusIndexLabelEventIDEqual    = "e4" // perfect-match of EventID
	EventStatusIndexLabelEventIDLike     = "e3" // like-match of EventID
	EventStatusIndexLabelEventIDPrefix   = "e1" // prefix-match of EventID
	EventStatusIndexLabelEventIDSuffix   = "e2" // suffix-match of EventID
	EventStatusIndexLabelStatusPrefix    = "s1" // prefix-match of Status
	EventStatusIndexLabelStatusSuffix    = "s2" // suffix-match of Status
	EventStatusIndexLabelStatusLike      = "s3" // like-match of Status
	EventStatusIndexLabelStatusEqual     = "s4" // perfect-match of Status
	EventStatusIndexLabelCreatedAtPrefix = "c1" // prefix-match of CreatedAt
	EventStatusIndexLabelCreatedAtSuffix = "c2" // suffix-match of CreatedAt
	EventStatusIndexLabelCreatedAtLike   = "c3" // like-match of CreatedAt
	EventStatusIndexLabelCreatedAtEqual  = "c4" // perfect-match of CreatedAt
	EventStatusIndexLabelCreatedByEqual  = "c8" // perfect-match of CreatedBy
	EventStatusIndexLabelCreatedByLike   = "c7" // like-match of CreatedBy
	EventStatusIndexLabelCreatedByPrefix = "c5" // prefix-match of CreatedBy
	EventStatusIndexLabelCreatedBySuffix = "c6" // suffix-match of CreatedBy
	EventStatusIndexLabelUpdatedAtPrefix = "u1" // prefix-match of UpdatedAt
	EventStatusIndexLabelUpdatedAtSuffix = "u2" // suffix-match of UpdatedAt
	EventStatusIndexLabelUpdatedAtLike   = "u3" // like-match of UpdatedAt
	EventStatusIndexLabelUpdatedAtEqual  = "u4" // perfect-match of UpdatedAt
	EventStatusIndexLabelUpdatedByEqual  = "u8" // perfect-match of UpdatedBy
	EventStatusIndexLabelUpdatedByLike   = "u7" // like-match of UpdatedBy
	EventStatusIndexLabelUpdatedByPrefix = "u5" // prefix-match of UpdatedBy
	EventStatusIndexLabelUpdatedBySuffix = "u6" // suffix-match of UpdatedBy
	EventStatusIndexLabelDeletedAtPrefix = "d1" // prefix-match of DeletedAt
	EventStatusIndexLabelDeletedAtSuffix = "d2" // suffix-match of DeletedAt
	EventStatusIndexLabelDeletedAtLike   = "d3" // like-match of DeletedAt
	EventStatusIndexLabelDeletedAtEqual  = "d4" // perfect-match of DeletedAt
	EventStatusIndexLabelDeletedByEqual  = "d8" // perfect-match of DeletedBy
	EventStatusIndexLabelDeletedByLike   = "d7" // like-match of DeletedBy
	EventStatusIndexLabelDeletedByPrefix = "d5" // prefix-match of DeletedBy
	EventStatusIndexLabelDeletedBySuffix = "d6" // suffix-match of DeletedBy
	EventStatusIndexLabelVersionPrefix   = "v1" // prefix-match of Version
	EventStatusIndexLabelVersionSuffix   = "v2" // suffix-match of Version
	EventStatusIndexLabelVersionLike     = "v3" // like-match of Version
	EventStatusIndexLabelVersionEqual    = "v4" // perfect-match of Version
)
