// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package infrastructures

const (
	GCASProportionCostIndexLabelEventIDEqual    = "e4" // perfect-match of EventID
	GCASProportionCostIndexLabelEventIDLike     = "e3" // like-match of EventID
	GCASProportionCostIndexLabelEventIDPrefix   = "e1" // prefix-match of EventID
	GCASProportionCostIndexLabelEventIDSuffix   = "e2" // suffix-match of EventID
	GCASProportionCostIndexLabelAccountIDEqual  = "a4" // perfect-match of AccountID
	GCASProportionCostIndexLabelAccountIDLike   = "a3" // like-match of AccountID
	GCASProportionCostIndexLabelAccountIDPrefix = "a1" // prefix-match of AccountID
	GCASProportionCostIndexLabelAccountIDSuffix = "a2" // suffix-match of AccountID
	GCASProportionCostIndexLabelCreatedAtPrefix = "c1" // prefix-match of CreatedAt
	GCASProportionCostIndexLabelCreatedAtSuffix = "c2" // suffix-match of CreatedAt
	GCASProportionCostIndexLabelCreatedAtLike   = "c3" // like-match of CreatedAt
	GCASProportionCostIndexLabelCreatedAtEqual  = "c4" // perfect-match of CreatedAt
	GCASProportionCostIndexLabelCreatedByEqual  = "c8" // perfect-match of CreatedBy
	GCASProportionCostIndexLabelCreatedByLike   = "c7" // like-match of CreatedBy
	GCASProportionCostIndexLabelCreatedByPrefix = "c5" // prefix-match of CreatedBy
	GCASProportionCostIndexLabelCreatedBySuffix = "c6" // suffix-match of CreatedBy
	GCASProportionCostIndexLabelUpdatedAtPrefix = "u1" // prefix-match of UpdatedAt
	GCASProportionCostIndexLabelUpdatedAtSuffix = "u2" // suffix-match of UpdatedAt
	GCASProportionCostIndexLabelUpdatedAtLike   = "u3" // like-match of UpdatedAt
	GCASProportionCostIndexLabelUpdatedAtEqual  = "u4" // perfect-match of UpdatedAt
	GCASProportionCostIndexLabelUpdatedByEqual  = "u8" // perfect-match of UpdatedBy
	GCASProportionCostIndexLabelUpdatedByLike   = "u7" // like-match of UpdatedBy
	GCASProportionCostIndexLabelUpdatedByPrefix = "u5" // prefix-match of UpdatedBy
	GCASProportionCostIndexLabelUpdatedBySuffix = "u6" // suffix-match of UpdatedBy
	GCASProportionCostIndexLabelDeletedAtPrefix = "d1" // prefix-match of DeletedAt
	GCASProportionCostIndexLabelDeletedAtSuffix = "d2" // suffix-match of DeletedAt
	GCASProportionCostIndexLabelDeletedAtLike   = "d3" // like-match of DeletedAt
	GCASProportionCostIndexLabelDeletedAtEqual  = "d4" // perfect-match of DeletedAt
	GCASProportionCostIndexLabelDeletedByEqual  = "d8" // perfect-match of DeletedBy
	GCASProportionCostIndexLabelDeletedByLike   = "d7" // like-match of DeletedBy
	GCASProportionCostIndexLabelDeletedByPrefix = "d5" // prefix-match of DeletedBy
	GCASProportionCostIndexLabelDeletedBySuffix = "d6" // suffix-match of DeletedBy
	GCASProportionCostIndexLabelVersionPrefix   = "v1" // prefix-match of Version
	GCASProportionCostIndexLabelVersionSuffix   = "v2" // suffix-match of Version
	GCASProportionCostIndexLabelVersionLike     = "v3" // like-match of Version
	GCASProportionCostIndexLabelVersionEqual    = "v4" // perfect-match of Version
)
