// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package infrastructures

const (
	OrgCSPAccountIndexLabelEventIDEqual               = "e4"  // perfect-match of EventID
	OrgCSPAccountIndexLabelEventIDLike                = "e3"  // like-match of EventID
	OrgCSPAccountIndexLabelEventIDPrefix              = "e1"  // prefix-match of EventID
	OrgCSPAccountIndexLabelEventIDSuffix              = "e2"  // suffix-match of EventID
	OrgCSPAccountIndexLabelGCASProportionCostIDEqual  = "g4"  // perfect-match of GCASProportionCostID
	OrgCSPAccountIndexLabelGCASProportionCostIDLike   = "g3"  // like-match of GCASProportionCostID
	OrgCSPAccountIndexLabelGCASProportionCostIDPrefix = "g1"  // prefix-match of GCASProportionCostID
	OrgCSPAccountIndexLabelGCASProportionCostIDSuffix = "g2"  // suffix-match of GCASProportionCostID
	OrgCSPAccountIndexLabelGCASAccountCostIDEqual     = "g8"  // perfect-match of GCASAccountCostID
	OrgCSPAccountIndexLabelGCASAccountCostIDLike      = "g7"  // like-match of GCASAccountCostID
	OrgCSPAccountIndexLabelGCASAccountCostIDPrefix    = "g5"  // prefix-match of GCASAccountCostID
	OrgCSPAccountIndexLabelGCASAccountCostIDSuffix    = "g6"  // suffix-match of GCASAccountCostID
	OrgCSPAccountIndexLabelOrganizationEqual          = "o4"  // perfect-match of Organization
	OrgCSPAccountIndexLabelOrganizationLike           = "o3"  // like-match of Organization
	OrgCSPAccountIndexLabelOrganizationPrefix         = "o1"  // prefix-match of Organization
	OrgCSPAccountIndexLabelOrganizationSuffix         = "o2"  // suffix-match of Organization
	OrgCSPAccountIndexLabelCSPEqual                   = "c4"  // perfect-match of CSP
	OrgCSPAccountIndexLabelCSPLike                    = "c3"  // like-match of CSP
	OrgCSPAccountIndexLabelCSPPrefix                  = "c1"  // prefix-match of CSP
	OrgCSPAccountIndexLabelCSPSuffix                  = "c2"  // suffix-match of CSP
	OrgCSPAccountIndexLabelAccountIDEqual             = "a4"  // perfect-match of AccountID
	OrgCSPAccountIndexLabelAccountIDLike              = "a3"  // like-match of AccountID
	OrgCSPAccountIndexLabelAccountIDPrefix            = "a1"  // prefix-match of AccountID
	OrgCSPAccountIndexLabelAccountIDSuffix            = "a2"  // suffix-match of AccountID
	OrgCSPAccountIndexLabelCostPrefix                 = "c5"  // prefix-match of Cost
	OrgCSPAccountIndexLabelCostSuffix                 = "c6"  // suffix-match of Cost
	OrgCSPAccountIndexLabelCostLike                   = "c7"  // like-match of Cost
	OrgCSPAccountIndexLabelCostEqual                  = "c8"  // perfect-match of Cost
	OrgCSPAccountIndexLabelBillingUnitIDEqual         = "b4"  // perfect-match of BillingUnitID
	OrgCSPAccountIndexLabelBillingUnitIDLike          = "b3"  // like-match of BillingUnitID
	OrgCSPAccountIndexLabelBillingUnitIDPrefix        = "b1"  // prefix-match of BillingUnitID
	OrgCSPAccountIndexLabelBillingUnitIDSuffix        = "b2"  // suffix-match of BillingUnitID
	OrgCSPAccountIndexLabelCreatedAtPrefix            = "c9"  // prefix-match of CreatedAt
	OrgCSPAccountIndexLabelCreatedAtSuffix            = "cr1" // suffix-match of CreatedAt
	OrgCSPAccountIndexLabelCreatedAtLike              = "cr2" // like-match of CreatedAt
	OrgCSPAccountIndexLabelCreatedAtEqual             = "cr3" // perfect-match of CreatedAt
	OrgCSPAccountIndexLabelCreatedByEqual             = "cr7" // perfect-match of CreatedBy
	OrgCSPAccountIndexLabelCreatedByLike              = "cr6" // like-match of CreatedBy
	OrgCSPAccountIndexLabelCreatedByPrefix            = "cr4" // prefix-match of CreatedBy
	OrgCSPAccountIndexLabelCreatedBySuffix            = "cr5" // suffix-match of CreatedBy
	OrgCSPAccountIndexLabelUpdatedAtPrefix            = "u1"  // prefix-match of UpdatedAt
	OrgCSPAccountIndexLabelUpdatedAtSuffix            = "u2"  // suffix-match of UpdatedAt
	OrgCSPAccountIndexLabelUpdatedAtLike              = "u3"  // like-match of UpdatedAt
	OrgCSPAccountIndexLabelUpdatedAtEqual             = "u4"  // perfect-match of UpdatedAt
	OrgCSPAccountIndexLabelUpdatedByEqual             = "u8"  // perfect-match of UpdatedBy
	OrgCSPAccountIndexLabelUpdatedByLike              = "u7"  // like-match of UpdatedBy
	OrgCSPAccountIndexLabelUpdatedByPrefix            = "u5"  // prefix-match of UpdatedBy
	OrgCSPAccountIndexLabelUpdatedBySuffix            = "u6"  // suffix-match of UpdatedBy
	OrgCSPAccountIndexLabelDeletedAtPrefix            = "d1"  // prefix-match of DeletedAt
	OrgCSPAccountIndexLabelDeletedAtSuffix            = "d2"  // suffix-match of DeletedAt
	OrgCSPAccountIndexLabelDeletedAtLike              = "d3"  // like-match of DeletedAt
	OrgCSPAccountIndexLabelDeletedAtEqual             = "d4"  // perfect-match of DeletedAt
	OrgCSPAccountIndexLabelDeletedByEqual             = "d8"  // perfect-match of DeletedBy
	OrgCSPAccountIndexLabelDeletedByLike              = "d7"  // like-match of DeletedBy
	OrgCSPAccountIndexLabelDeletedByPrefix            = "d5"  // prefix-match of DeletedBy
	OrgCSPAccountIndexLabelDeletedBySuffix            = "d6"  // suffix-match of DeletedBy
	OrgCSPAccountIndexLabelVersionPrefix              = "v1"  // prefix-match of Version
	OrgCSPAccountIndexLabelVersionSuffix              = "v2"  // suffix-match of Version
	OrgCSPAccountIndexLabelVersionLike                = "v3"  // like-match of Version
	OrgCSPAccountIndexLabelVersionEqual               = "v4"  // perfect-match of Version
)
