// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package infrastructures

const (
	PaymentIndexLabelEventIDEqual       = "e4"  // perfect-match of EventID
	PaymentIndexLabelEventIDLike        = "e3"  // like-match of EventID
	PaymentIndexLabelEventIDPrefix      = "e1"  // prefix-match of EventID
	PaymentIndexLabelEventIDSuffix      = "e2"  // suffix-match of EventID
	PaymentIndexLabelBillingIDEqual     = "b4"  // perfect-match of BillingID
	PaymentIndexLabelBillingIDLike      = "b3"  // like-match of BillingID
	PaymentIndexLabelBillingIDPrefix    = "b1"  // prefix-match of BillingID
	PaymentIndexLabelBillingIDSuffix    = "b2"  // suffix-match of BillingID
	PaymentIndexLabelPaymentNumIDEqual  = "p4"  // perfect-match of PaymentNumID
	PaymentIndexLabelPaymentNumIDLike   = "p3"  // like-match of PaymentNumID
	PaymentIndexLabelPaymentNumIDPrefix = "p1"  // prefix-match of PaymentNumID
	PaymentIndexLabelPaymentNumIDSuffix = "p2"  // suffix-match of PaymentNumID
	PaymentIndexLabelCostPrefix         = "c1"  // prefix-match of Cost
	PaymentIndexLabelCostSuffix         = "c2"  // suffix-match of Cost
	PaymentIndexLabelCostLike           = "c3"  // like-match of Cost
	PaymentIndexLabelCostEqual          = "c4"  // perfect-match of Cost
	PaymentIndexLabelCreatedAtPrefix    = "c5"  // prefix-match of CreatedAt
	PaymentIndexLabelCreatedAtSuffix    = "c6"  // suffix-match of CreatedAt
	PaymentIndexLabelCreatedAtLike      = "c7"  // like-match of CreatedAt
	PaymentIndexLabelCreatedAtEqual     = "c8"  // perfect-match of CreatedAt
	PaymentIndexLabelCreatedByEqual     = "cr3" // perfect-match of CreatedBy
	PaymentIndexLabelCreatedByLike      = "cr2" // like-match of CreatedBy
	PaymentIndexLabelCreatedByPrefix    = "c9"  // prefix-match of CreatedBy
	PaymentIndexLabelCreatedBySuffix    = "cr1" // suffix-match of CreatedBy
	PaymentIndexLabelUpdatedAtPrefix    = "u1"  // prefix-match of UpdatedAt
	PaymentIndexLabelUpdatedAtSuffix    = "u2"  // suffix-match of UpdatedAt
	PaymentIndexLabelUpdatedAtLike      = "u3"  // like-match of UpdatedAt
	PaymentIndexLabelUpdatedAtEqual     = "u4"  // perfect-match of UpdatedAt
	PaymentIndexLabelUpdatedByEqual     = "u8"  // perfect-match of UpdatedBy
	PaymentIndexLabelUpdatedByLike      = "u7"  // like-match of UpdatedBy
	PaymentIndexLabelUpdatedByPrefix    = "u5"  // prefix-match of UpdatedBy
	PaymentIndexLabelUpdatedBySuffix    = "u6"  // suffix-match of UpdatedBy
	PaymentIndexLabelDeletedAtPrefix    = "d1"  // prefix-match of DeletedAt
	PaymentIndexLabelDeletedAtSuffix    = "d2"  // suffix-match of DeletedAt
	PaymentIndexLabelDeletedAtLike      = "d3"  // like-match of DeletedAt
	PaymentIndexLabelDeletedAtEqual     = "d4"  // perfect-match of DeletedAt
	PaymentIndexLabelDeletedByEqual     = "d8"  // perfect-match of DeletedBy
	PaymentIndexLabelDeletedByLike      = "d7"  // like-match of DeletedBy
	PaymentIndexLabelDeletedByPrefix    = "d5"  // prefix-match of DeletedBy
	PaymentIndexLabelDeletedBySuffix    = "d6"  // suffix-match of DeletedBy
	PaymentIndexLabelVersionPrefix      = "v1"  // prefix-match of Version
	PaymentIndexLabelVersionSuffix      = "v2"  // suffix-match of Version
	PaymentIndexLabelVersionLike        = "v3"  // like-match of Version
	PaymentIndexLabelVersionEqual       = "v4"  // perfect-match of Version
)
