// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package infrastructures

const (
	PaymentNumIndexLabelEventIDEqual        = "e4"  // perfect-match of EventID
	PaymentNumIndexLabelEventIDLike         = "e3"  // like-match of EventID
	PaymentNumIndexLabelEventIDPrefix       = "e1"  // prefix-match of EventID
	PaymentNumIndexLabelEventIDSuffix       = "e2"  // suffix-match of EventID
	PaymentNumIndexLabelBillingIDEqual      = "b4"  // perfect-match of BillingID
	PaymentNumIndexLabelBillingIDLike       = "b3"  // like-match of BillingID
	PaymentNumIndexLabelBillingIDPrefix     = "b1"  // prefix-match of BillingID
	PaymentNumIndexLabelBillingIDSuffix     = "b2"  // suffix-match of BillingID
	PaymentNumIndexLabelBillingUnitIDEqual  = "b8"  // perfect-match of BillingUnitID
	PaymentNumIndexLabelBillingUnitIDLike   = "b7"  // like-match of BillingUnitID
	PaymentNumIndexLabelBillingUnitIDPrefix = "b5"  // prefix-match of BillingUnitID
	PaymentNumIndexLabelBillingUnitIDSuffix = "b6"  // suffix-match of BillingUnitID
	PaymentNumIndexLabelPaymentNumEqual     = "p4"  // perfect-match of PaymentNum
	PaymentNumIndexLabelPaymentNumLike      = "p3"  // like-match of PaymentNum
	PaymentNumIndexLabelPaymentNumPrefix    = "p1"  // prefix-match of PaymentNum
	PaymentNumIndexLabelPaymentNumSuffix    = "p2"  // suffix-match of PaymentNum
	PaymentNumIndexLabelCostPrefix          = "c1"  // prefix-match of Cost
	PaymentNumIndexLabelCostSuffix          = "c2"  // suffix-match of Cost
	PaymentNumIndexLabelCostLike            = "c3"  // like-match of Cost
	PaymentNumIndexLabelCostEqual           = "c4"  // perfect-match of Cost
	PaymentNumIndexLabelCreatedAtPrefix     = "c5"  // prefix-match of CreatedAt
	PaymentNumIndexLabelCreatedAtSuffix     = "c6"  // suffix-match of CreatedAt
	PaymentNumIndexLabelCreatedAtLike       = "c7"  // like-match of CreatedAt
	PaymentNumIndexLabelCreatedAtEqual      = "c8"  // perfect-match of CreatedAt
	PaymentNumIndexLabelCreatedByEqual      = "cr3" // perfect-match of CreatedBy
	PaymentNumIndexLabelCreatedByLike       = "cr2" // like-match of CreatedBy
	PaymentNumIndexLabelCreatedByPrefix     = "c9"  // prefix-match of CreatedBy
	PaymentNumIndexLabelCreatedBySuffix     = "cr1" // suffix-match of CreatedBy
	PaymentNumIndexLabelUpdatedAtPrefix     = "u1"  // prefix-match of UpdatedAt
	PaymentNumIndexLabelUpdatedAtSuffix     = "u2"  // suffix-match of UpdatedAt
	PaymentNumIndexLabelUpdatedAtLike       = "u3"  // like-match of UpdatedAt
	PaymentNumIndexLabelUpdatedAtEqual      = "u4"  // perfect-match of UpdatedAt
	PaymentNumIndexLabelUpdatedByEqual      = "u8"  // perfect-match of UpdatedBy
	PaymentNumIndexLabelUpdatedByLike       = "u7"  // like-match of UpdatedBy
	PaymentNumIndexLabelUpdatedByPrefix     = "u5"  // prefix-match of UpdatedBy
	PaymentNumIndexLabelUpdatedBySuffix     = "u6"  // suffix-match of UpdatedBy
	PaymentNumIndexLabelDeletedAtPrefix     = "d1"  // prefix-match of DeletedAt
	PaymentNumIndexLabelDeletedAtSuffix     = "d2"  // suffix-match of DeletedAt
	PaymentNumIndexLabelDeletedAtLike       = "d3"  // like-match of DeletedAt
	PaymentNumIndexLabelDeletedAtEqual      = "d4"  // perfect-match of DeletedAt
	PaymentNumIndexLabelDeletedByEqual      = "d8"  // perfect-match of DeletedBy
	PaymentNumIndexLabelDeletedByLike       = "d7"  // like-match of DeletedBy
	PaymentNumIndexLabelDeletedByPrefix     = "d5"  // prefix-match of DeletedBy
	PaymentNumIndexLabelDeletedBySuffix     = "d6"  // suffix-match of DeletedBy
	PaymentNumIndexLabelVersionPrefix       = "v1"  // prefix-match of Version
	PaymentNumIndexLabelVersionSuffix       = "v2"  // suffix-match of Version
	PaymentNumIndexLabelVersionLike         = "v3"  // like-match of Version
	PaymentNumIndexLabelVersionEqual        = "v4"  // perfect-match of Version
)
