// Code generated by volcago. DO NOT EDIT.
// generated version: v1.11.1
package infrastructures

const (
	REPSAuthIndexLabelEventIDEqual       = "e4" // perfect-match of EventID
	REPSAuthIndexLabelEventIDLike        = "e3" // like-match of EventID
	REPSAuthIndexLabelEventIDPrefix      = "e1" // prefix-match of EventID
	REPSAuthIndexLabelEventIDSuffix      = "e2" // suffix-match of EventID
	REPSAuthIndexLabelAccessTokenEqual   = "a4" // perfect-match of AccessToken
	REPSAuthIndexLabelAccessTokenLike    = "a3" // like-match of AccessToken
	REPSAuthIndexLabelAccessTokenPrefix  = "a1" // prefix-match of AccessToken
	REPSAuthIndexLabelAccessTokenSuffix  = "a2" // suffix-match of AccessToken
	REPSAuthIndexLabelRefreshTokenEqual  = "r4" // perfect-match of RefreshToken
	REPSAuthIndexLabelRefreshTokenLike   = "r3" // like-match of RefreshToken
	REPSAuthIndexLabelRefreshTokenPrefix = "r1" // prefix-match of RefreshToken
	REPSAuthIndexLabelRefreshTokenSuffix = "r2" // suffix-match of RefreshToken
	REPSAuthIndexLabelCreatedAtPrefix    = "c1" // prefix-match of CreatedAt
	REPSAuthIndexLabelCreatedAtSuffix    = "c2" // suffix-match of CreatedAt
	REPSAuthIndexLabelCreatedAtLike      = "c3" // like-match of CreatedAt
	REPSAuthIndexLabelCreatedAtEqual     = "c4" // perfect-match of CreatedAt
	REPSAuthIndexLabelCreatedByEqual     = "c8" // perfect-match of CreatedBy
	REPSAuthIndexLabelCreatedByLike      = "c7" // like-match of CreatedBy
	REPSAuthIndexLabelCreatedByPrefix    = "c5" // prefix-match of CreatedBy
	REPSAuthIndexLabelCreatedBySuffix    = "c6" // suffix-match of CreatedBy
	REPSAuthIndexLabelUpdatedAtPrefix    = "u1" // prefix-match of UpdatedAt
	REPSAuthIndexLabelUpdatedAtSuffix    = "u2" // suffix-match of UpdatedAt
	REPSAuthIndexLabelUpdatedAtLike      = "u3" // like-match of UpdatedAt
	REPSAuthIndexLabelUpdatedAtEqual     = "u4" // perfect-match of UpdatedAt
	REPSAuthIndexLabelUpdatedByEqual     = "u8" // perfect-match of UpdatedBy
	REPSAuthIndexLabelUpdatedByLike      = "u7" // like-match of UpdatedBy
	REPSAuthIndexLabelUpdatedByPrefix    = "u5" // prefix-match of UpdatedBy
	REPSAuthIndexLabelUpdatedBySuffix    = "u6" // suffix-match of UpdatedBy
	REPSAuthIndexLabelDeletedAtPrefix    = "d1" // prefix-match of DeletedAt
	REPSAuthIndexLabelDeletedAtSuffix    = "d2" // suffix-match of DeletedAt
	REPSAuthIndexLabelDeletedAtLike      = "d3" // like-match of DeletedAt
	REPSAuthIndexLabelDeletedAtEqual     = "d4" // perfect-match of DeletedAt
	REPSAuthIndexLabelDeletedByEqual     = "d8" // perfect-match of DeletedBy
	REPSAuthIndexLabelDeletedByLike      = "d7" // like-match of DeletedBy
	REPSAuthIndexLabelDeletedByPrefix    = "d5" // prefix-match of DeletedBy
	REPSAuthIndexLabelDeletedBySuffix    = "d6" // suffix-match of DeletedBy
	REPSAuthIndexLabelVersionPrefix      = "v1" // prefix-match of Version
	REPSAuthIndexLabelVersionSuffix      = "v2" // suffix-match of Version
	REPSAuthIndexLabelVersionLike        = "v3" // like-match of Version
	REPSAuthIndexLabelVersionEqual       = "v4" // perfect-match of Version
)
