// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../repositoryimpl/mocks/base_repository_mock.go -package=mockrepositories
//

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBaseRepository is a mock of BaseRepository interface.
type MockBaseRepository[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockBaseRepositoryMockRecorder[T]
}

// MockBaseRepositoryMockRecorder is the mock recorder for MockBaseRepository.
type MockBaseRepositoryMockRecorder[T any] struct {
	mock *MockBaseRepository[T]
}

// NewMockBaseRepository creates a new mock instance.
func NewMockBaseRepository[T any](ctrl *gomock.Controller) *MockBaseRepository[T] {
	mock := &MockBaseRepository[T]{ctrl: ctrl}
	mock.recorder = &MockBaseRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseRepository[T]) EXPECT() *MockBaseRepositoryMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m *MockBaseRepository[T]) Create(ctx context.Context, entity *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBaseRepositoryMockRecorder[T]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBaseRepository[T])(nil).Create), ctx, entity)
}

// GetByID mocks base method.
func (m *MockBaseRepository[T]) GetByID(ctx context.Context, id string) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBaseRepositoryMockRecorder[T]) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBaseRepository[T])(nil).GetByID), ctx, id)
}
